import React, { useState } from 'react';
import {
  Copy,
  Check,
  RotateCcw,
  Sparkles,
  Hash,
  Search,
  MessageSquare,
  Building,
  Languages,
  Tag,
  Phone,
  Globe,
  DollarSign,
  Gift,
  Share2,
  Bookmark,
  Trash2,
  ExternalLink,
} from 'lucide-react';
import { AnalysisResult, MarketingFormula } from '../types';

interface ResultsDisplayProps {
  result: AnalysisResult;
  onRegenerate: () => void;
  onClear: () => void;
  onSelectFormula?: (formula: MarketingFormula) => void;
  isRegenerating: boolean;
}

export const ResultsDisplay: React.FC<ResultsDisplayProps> = ({
  result,
  onRegenerate,
  onClear,
  onSelectFormula,
  isRegenerating,
}) => {
  const [copiedSection, setCopiedSection] = useState<string | null>(null);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const copyToClipboard = async (text: string, label: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedSection(label);
      setToastMessage(`Copied ${label} to clipboard!`);
      setTimeout(() => {
        setCopiedSection(null);
        setToastMessage(null);
      }, 3000);
    } catch {
      try {
        const textarea = document.createElement('textarea');
        textarea.value = text;
        document.body.appendChild(textarea);
        textarea.select();
        document.execCommand('copy');
        document.body.removeChild(textarea);
        setCopiedSection(label);
        setToastMessage(`Copied ${label} to clipboard!`);
        setTimeout(() => {
          setCopiedSection(null);
          setToastMessage(null);
        }, 3000);
      } catch {
        // Fallback silently
      }
    }
  };

  const getAllHashtagsText = () => {
    return result.hashtags.all.join(' ');
  };

  const getAllKeywordsText = () => {
    return result.seoKeywords.all.join(', ');
  };

  const getFullBundleText = () => {
    return `=== AEZEY AI STUDIO GENERATED CONTENT ===
${result.formula && result.formula !== 'standard' ? `\n📐 MARKETING FORMULA:\n${result.formula}\n` : ''}
📌 PRIMARY CAPTION:
${result.primaryCaption}

📌 ALTERNATIVE CAPTION:
${result.alternativeCaption}

🔗 SEO-FRIENDLY URL SLUG:
${result.urlSlug || 'content-post'}

🏷️ HASHTAGS:
${getAllHashtagsText()}

🔍 SEO KEYWORDS:
${getAllKeywordsText()}

🎯 CALL TO ACTION:
${result.callToAction}

📝 CONTENT SUMMARY:
${result.contentSummary}

⚡ DETECTED CONTEXT:
• Brand: ${result.detectedContext.detectedBrand || 'None detected (Dynamic)'}
• Language: ${result.detectedContext.detectedLanguage}
• Topic: ${result.detectedContext.mainTopic}
• Promotional Intent: ${result.detectedContext.promotionalIntent}
${
  result.detectedContext.contactInfoFound?.phone
    ? `• Phone: ${result.detectedContext.contactInfoFound.phone}\n`
    : ''
}${
      result.detectedContext.contactInfoFound?.website
        ? `• Website: ${result.detectedContext.contactInfoFound.website}\n`
        : ''
    }
Generated by AEZEY AI Studio - AI-Powered Content Creation for Smarter Social Media`;
  };

  return (
    <div className="w-full space-y-6 mt-8 animate-in fade-in duration-300">
      {/* Toast Notification */}
      {toastMessage && (
        <div className="fixed bottom-6 right-6 z-50 bg-slate-900 border border-cyan-500/50 text-white px-4 py-3 rounded-xl shadow-2xl flex items-center gap-3 animate-in slide-in-from-bottom-3 duration-200">
          <div className="w-6 h-6 rounded-full bg-cyan-500/20 text-cyan-400 flex items-center justify-center">
            <Check className="w-3.5 h-3.5" />
          </div>
          <span className="text-sm font-semibold">{toastMessage}</span>
        </div>
      )}

      {/* Top Action Bar */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-4 sm:p-5 flex flex-wrap items-center justify-between gap-4 backdrop-blur-md">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-blue-600 to-cyan-500 flex items-center justify-center text-white shadow-md shadow-blue-500/20">
            <Sparkles className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-white flex items-center gap-2">
              Generated Content Package
              <span className="text-xs px-2 py-0.5 rounded-full font-medium bg-cyan-950 text-cyan-300 border border-cyan-500/30">
                Ready to Publish
              </span>
            </h3>
            <p className="text-xs text-slate-400">
              High-converting social copy, targeted hashtags, and high-intent SEO
            </p>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-2.5">
          <button
            onClick={() => copyToClipboard(getFullBundleText(), 'Full Package')}
            className="px-4 py-2 rounded-xl text-xs font-bold bg-cyan-500 hover:bg-cyan-400 text-slate-950 transition-all flex items-center gap-1.5 shadow-md shadow-cyan-500/20"
          >
            {copiedSection === 'Full Package' ? (
              <Check className="w-3.5 h-3.5" />
            ) : (
              <Copy className="w-3.5 h-3.5" />
            )}
            Copy All Content
          </button>

          <button
            onClick={onRegenerate}
            disabled={isRegenerating}
            className="px-3.5 py-2 rounded-xl text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-white transition-colors flex items-center gap-1.5 border border-slate-700"
          >
            <RotateCcw className={`w-3.5 h-3.5 ${isRegenerating ? 'animate-spin' : ''}`} />
            Regenerate
          </button>

          <button
            onClick={onClear}
            className="px-3.5 py-2 rounded-xl text-xs font-semibold bg-slate-800/80 hover:bg-red-950/80 hover:text-red-300 text-slate-400 transition-colors flex items-center gap-1.5 border border-slate-700/80"
          >
            <Trash2 className="w-3.5 h-3.5" />
            Clear Results
          </button>
        </div>
      </div>

      {/* Marketing Formulas Action Bar */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-4 sm:p-5 flex flex-wrap items-center justify-between gap-4 backdrop-blur-md">
        <div className="flex items-center gap-2.5">
          <span className="w-2.5 h-2.5 rounded-full bg-cyan-400 animate-pulse" />
          <h4 className="text-sm font-bold text-white flex items-center gap-2">
            Marketing Copywriting Formulas:
            {result.formula && result.formula !== 'standard' && (
              <span className="text-xs px-2.5 py-0.5 rounded-full font-bold bg-cyan-950 text-cyan-300 border border-cyan-500/40">
                Active: {result.formula}
              </span>
            )}
          </h4>
          <span className="text-xs text-slate-400 hidden lg:inline">
            • 1-click re-generation in formula format
          </span>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          {/* AIDA */}
          <button
            type="button"
            onClick={() => onSelectFormula?.('AIDA')}
            disabled={isRegenerating}
            className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all flex items-center gap-1.5 border cursor-pointer ${
              result.formula === 'AIDA'
                ? 'bg-cyan-500 text-slate-950 border-cyan-400 shadow-md shadow-cyan-500/25 ring-1 ring-cyan-400'
                : 'bg-slate-800 hover:bg-slate-700 text-slate-200 border-slate-700 hover:border-cyan-500/40'
            }`}
          >
            <span className={`w-1.5 h-1.5 rounded-full ${result.formula === 'AIDA' ? 'bg-slate-950' : 'bg-cyan-400'}`} />
            AIDA (Attention • Interest • Desire • Action)
          </button>

          {/* PAS */}
          <button
            type="button"
            onClick={() => onSelectFormula?.('PAS')}
            disabled={isRegenerating}
            className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all flex items-center gap-1.5 border cursor-pointer ${
              result.formula === 'PAS'
                ? 'bg-amber-500 text-slate-950 border-amber-400 shadow-md shadow-amber-500/25 ring-1 ring-amber-400'
                : 'bg-slate-800 hover:bg-slate-700 text-slate-200 border-slate-700 hover:border-amber-500/40'
            }`}
          >
            <span className={`w-1.5 h-1.5 rounded-full ${result.formula === 'PAS' ? 'bg-slate-950' : 'bg-amber-400'}`} />
            PAS (Problem • Agitate • Solution)
          </button>

          {/* BAB */}
          <button
            type="button"
            onClick={() => onSelectFormula?.('BAB')}
            disabled={isRegenerating}
            className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all flex items-center gap-1.5 border cursor-pointer ${
              result.formula === 'BAB'
                ? 'bg-purple-500 text-white border-purple-400 shadow-md shadow-purple-500/25 ring-1 ring-purple-400'
                : 'bg-slate-800 hover:bg-slate-700 text-slate-200 border-slate-700 hover:border-purple-500/40'
            }`}
          >
            <span className={`w-1.5 h-1.5 rounded-full ${result.formula === 'BAB' ? 'bg-white' : 'bg-purple-400'}`} />
            BAB (Before • After • Bridge)
          </button>
        </div>
      </div>

      {/* Notice Banner if Adaptive Synthesis */}
      {result.authNotice && (
        <div className="bg-gradient-to-r from-blue-950/70 to-slate-900/90 border border-cyan-500/30 rounded-2xl p-4 flex items-start gap-3 text-xs text-cyan-200">
          <Sparkles className="w-4 h-4 text-cyan-400 shrink-0 mt-0.5" />
          <div className="flex-1">
            <span className="font-semibold text-white block mb-0.5">Adaptive Multi-Modal Engine</span>
            <p className="text-slate-300 leading-relaxed">{result.authNotice}</p>
          </div>
        </div>
      )}

      {/* Dynamic Brand & Detected Context Banner */}
      <div className="bg-slate-900/80 border border-slate-800/90 rounded-2xl p-5 backdrop-blur-md">
        <div className="flex items-center justify-between pb-3 border-b border-slate-800/80">
          <span className="text-xs font-bold uppercase tracking-wider text-cyan-400 flex items-center gap-1.5">
            <Building className="w-3.5 h-3.5" />
            Dynamic Recognition & Context Intelligence
          </span>
          <span className="text-[11px] text-slate-400">Zero generic assumptions</span>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-4">
          {/* Detected Brand */}
          <div className="p-3.5 rounded-xl bg-slate-950/60 border border-slate-800">
            <span className="text-[11px] text-slate-400 uppercase tracking-wider font-semibold block">
              Recognized Brand
            </span>
            <div className="mt-1 flex items-center gap-2">
              <span className="font-bold text-base text-white">
                {result.detectedContext.detectedBrand || 'No fixed brand (Generic)'}
              </span>
            </div>
            <p className="text-[10px] text-slate-400 mt-1">
              {result.detectedContext.hasBrand
                ? 'Extracted directly from visible logo or typography'
                : 'No brand forced or hallucinated'}
            </p>
          </div>

          {/* Detected Language */}
          <div className="p-3.5 rounded-xl bg-slate-950/60 border border-slate-800">
            <span className="text-[11px] text-slate-400 uppercase tracking-wider font-semibold block">
              Language & Script
            </span>
            <div className="mt-1 flex items-center gap-2">
              <Languages className="w-4 h-4 text-cyan-400" />
              <span className="font-bold text-base text-cyan-300">
                {result.detectedContext.detectedLanguage}
              </span>
            </div>
            <p className="text-[10px] text-slate-400 mt-1">
              Tone: {result.detectedContext.tone}
            </p>
          </div>

          {/* Main Topic */}
          <div className="p-3.5 rounded-xl bg-slate-950/60 border border-slate-800">
            <span className="text-[11px] text-slate-400 uppercase tracking-wider font-semibold block">
              Topic & Audience
            </span>
            <span className="font-bold text-sm text-white mt-1 block line-clamp-1">
              {result.detectedContext.mainTopic}
            </span>
            <p className="text-[10px] text-slate-400 mt-1 line-clamp-1">
              Target: {result.detectedContext.targetAudience}
            </p>
          </div>

          {/* Promotional Intent */}
          <div className="p-3.5 rounded-xl bg-slate-950/60 border border-slate-800">
            <span className="text-[11px] text-slate-400 uppercase tracking-wider font-semibold block">
              Promotional Intent
            </span>
            <div className="mt-1 flex items-center gap-2">
              <span
                className={`text-xs px-2.5 py-0.5 rounded-full font-bold ${
                  result.detectedContext.promotionalIntent === 'High'
                    ? 'bg-amber-950 text-amber-300 border border-amber-500/30'
                    : 'bg-blue-950 text-blue-300 border border-blue-500/30'
                }`}
              >
                {result.detectedContext.promotionalIntent} Intent
              </span>
            </div>
            <p className="text-[10px] text-slate-400 mt-1">Tailored for maximum conversion</p>
          </div>
        </div>

        {/* Contact details found if any */}
        {(result.detectedContext.contactInfoFound?.phone ||
          result.detectedContext.contactInfoFound?.website ||
          result.detectedContext.contactInfoFound?.prices ||
          result.detectedContext.contactInfoFound?.offers) && (
          <div className="mt-4 pt-3 border-t border-slate-800/80 flex flex-wrap items-center gap-4 text-xs">
            <span className="text-slate-400 font-semibold">Extracted Visible Details:</span>
            {result.detectedContext.contactInfoFound.phone && (
              <span className="flex items-center gap-1 text-emerald-300 bg-emerald-950/60 px-2 py-0.5 rounded border border-emerald-500/30">
                <Phone className="w-3 h-3" />
                {result.detectedContext.contactInfoFound.phone}
              </span>
            )}
            {result.detectedContext.contactInfoFound.website && (
              <span className="flex items-center gap-1 text-blue-300 bg-blue-950/60 px-2 py-0.5 rounded border border-blue-500/30">
                <Globe className="w-3 h-3" />
                {result.detectedContext.contactInfoFound.website}
              </span>
            )}
            {result.detectedContext.contactInfoFound.prices && (
              <span className="flex items-center gap-1 text-amber-300 bg-amber-950/60 px-2 py-0.5 rounded border border-amber-500/30">
                <DollarSign className="w-3 h-3" />
                {result.detectedContext.contactInfoFound.prices}
              </span>
            )}
            {result.detectedContext.contactInfoFound.offers && (
              <span className="flex items-center gap-1 text-purple-300 bg-purple-950/60 px-2 py-0.5 rounded border border-purple-500/30">
                <Gift className="w-3 h-3" />
                {result.detectedContext.contactInfoFound.offers}
              </span>
            )}
          </div>
        )}
      </div>

      {/* Grid for Captions: Primary & Alternative */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Section 1: Primary Caption */}
        <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 flex flex-col justify-between backdrop-blur-md relative group hover:border-cyan-500/40 transition-colors">
          <div>
            <div className="flex items-center justify-between pb-3 border-b border-slate-800">
              <div className="flex items-center gap-2">
                <span className="w-2.5 h-2.5 rounded-full bg-cyan-400" />
                <h4 className="text-base font-bold text-white">Primary Social Media Caption</h4>
              </div>
              <span className="text-[11px] text-slate-400">Main Engaging Hook</span>
            </div>

            <div className="mt-4 text-slate-200 text-sm sm:text-base leading-relaxed whitespace-pre-wrap font-normal select-text">
              {result.primaryCaption}
            </div>
          </div>

          <div className="mt-6 pt-4 border-t border-slate-800 flex items-center justify-between">
            <span className="text-xs text-slate-400">
              {result.primaryCaption.split(/\s+/).filter(Boolean).length} words •{' '}
              {result.primaryCaption.length} characters
            </span>

            <button
              onClick={() => copyToClipboard(result.primaryCaption, 'Primary Caption')}
              className="px-3 py-1.5 rounded-lg text-xs font-semibold bg-slate-800 hover:bg-cyan-500 hover:text-slate-950 text-slate-200 transition-all flex items-center gap-1.5"
            >
              {copiedSection === 'Primary Caption' ? (
                <Check className="w-3.5 h-3.5" />
              ) : (
                <Copy className="w-3.5 h-3.5" />
              )}
              Copy Caption
            </button>
          </div>
        </div>

        {/* Section 2: Alternative Caption */}
        <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 flex flex-col justify-between backdrop-blur-md relative group hover:border-blue-500/40 transition-colors">
          <div>
            <div className="flex items-center justify-between pb-3 border-b border-slate-800">
              <div className="flex items-center gap-2">
                <span className="w-2.5 h-2.5 rounded-full bg-blue-400" />
                <h4 className="text-base font-bold text-white">Alternative Caption Variation</h4>
              </div>
              <span className="text-[11px] text-slate-400">Different Tone / Angle</span>
            </div>

            <div className="mt-4 text-slate-200 text-sm sm:text-base leading-relaxed whitespace-pre-wrap font-normal select-text">
              {result.alternativeCaption}
            </div>
          </div>

          <div className="mt-6 pt-4 border-t border-slate-800 flex items-center justify-between">
            <span className="text-xs text-slate-400">
              {result.alternativeCaption.split(/\s+/).filter(Boolean).length} words •{' '}
              {result.alternativeCaption.length} characters
            </span>

            <button
              onClick={() => copyToClipboard(result.alternativeCaption, 'Alternative Caption')}
              className="px-3 py-1.5 rounded-lg text-xs font-semibold bg-slate-800 hover:bg-blue-500 hover:text-white text-slate-200 transition-all flex items-center gap-1.5"
            >
              {copiedSection === 'Alternative Caption' ? (
                <Check className="w-3.5 h-3.5" />
              ) : (
                <Copy className="w-3.5 h-3.5" />
              )}
              Copy Alternative
            </button>
          </div>
        </div>
      </div>

      {/* Section 2.5: SEO-Friendly URL Slug */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 backdrop-blur-md relative hover:border-cyan-500/40 transition-colors">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between pb-4 border-b border-slate-800 gap-3">
          <div>
            <h4 className="text-base font-bold text-white flex items-center gap-2">
              <Globe className="w-4 h-4 text-cyan-400" />
              SEO-Friendly URL Slug
            </h4>
            <p className="text-xs text-slate-400 mt-0.5">
              Clean kebab-case slug generated strictly from your uploaded media content for blog posts, product pages, and social article previews
            </p>
          </div>

          <button
            onClick={() => copyToClipboard(result.urlSlug || 'media-content', 'URL Slug')}
            className="px-3.5 py-1.5 rounded-lg text-xs font-semibold bg-slate-800 hover:bg-cyan-500 hover:text-slate-950 text-slate-200 transition-all flex items-center gap-1.5"
          >
            {copiedSection === 'URL Slug' ? (
              <Check className="w-3.5 h-3.5" />
            ) : (
              <Copy className="w-3.5 h-3.5" />
            )}
            Copy Slug
          </button>
        </div>

        <div className="mt-4 flex flex-col md:flex-row items-stretch md:items-center justify-between gap-3 p-3.5 rounded-xl bg-slate-950 border border-slate-800">
          <div className="flex items-center gap-2 overflow-x-auto py-1">
            <span className="text-xs text-slate-500 select-none font-mono flex-shrink-0">
              https://yourdomain.com/posts/
            </span>
            <span className="text-sm font-bold text-cyan-300 font-mono tracking-tight select-all">
              {result.urlSlug || 'media-content'}
            </span>
          </div>

          <div className="flex items-center gap-2 flex-shrink-0 self-end md:self-auto">
            <span className="text-[11px] px-2.5 py-1 rounded-md bg-cyan-950/80 text-cyan-300 border border-cyan-800/40 font-mono">
              {(result.urlSlug || 'media-content').length} chars
            </span>
            <span className="text-[11px] px-2.5 py-1 rounded-md bg-slate-800 text-slate-300 border border-slate-700">
              kebab-case
            </span>
          </div>
        </div>
      </div>

      {/* Section 3: Hashtags */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 backdrop-blur-md">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between pb-4 border-b border-slate-800 gap-3">
          <div>
            <h4 className="text-base font-bold text-white flex items-center gap-2">
              <Hash className="w-4 h-4 text-cyan-400" />
              SEO-Friendly & Searchable Hashtags
            </h4>
            <p className="text-xs text-slate-400 mt-0.5">
              High-visibility mix of searchable product, industry, niche, topic, and audience tags
            </p>
          </div>

          <button
            onClick={() => copyToClipboard(getAllHashtagsText(), 'Hashtags')}
            className="px-3.5 py-1.5 rounded-lg text-xs font-semibold bg-slate-800 hover:bg-cyan-500 hover:text-slate-950 text-slate-200 transition-all flex items-center gap-1.5"
          >
            {copiedSection === 'Hashtags' ? (
              <Check className="w-3.5 h-3.5" />
            ) : (
              <Copy className="w-3.5 h-3.5" />
            )}
            Copy All Hashtags ({result.hashtags.all.length})
          </button>
        </div>

        {/* Categorized Hashtags */}
        <div className="space-y-4 mt-5">
          {/* Industry & Niche */}
          <div>
            <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider block mb-2">
              Industry & Niche Tags
            </span>
            <div className="flex flex-wrap gap-2">
              {[...result.hashtags.industry, ...result.hashtags.niche].map((tag, idx) => (
                <span
                  key={idx}
                  className="text-xs font-medium px-2.5 py-1 rounded-lg bg-slate-950 text-cyan-300 border border-slate-800 hover:border-cyan-500/40 transition-colors"
                >
                  {tag}
                </span>
              ))}
            </div>
          </div>

          {/* Topic & Audience */}
          <div>
            <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider block mb-2">
              Topic & Audience Tags
            </span>
            <div className="flex flex-wrap gap-2">
              {[...result.hashtags.topic, ...result.hashtags.audience].map((tag, idx) => (
                <span
                  key={idx}
                  className="text-xs font-medium px-2.5 py-1 rounded-lg bg-slate-950 text-blue-300 border border-slate-800 hover:border-blue-500/40 transition-colors"
                >
                  {tag}
                </span>
              ))}
            </div>
          </div>

          {/* Product & Location (if any) */}
          {((result.hashtags.productService?.length ?? 0) > 0 || (result.hashtags.location?.length ?? 0) > 0) && (
            <div>
              <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider block mb-2">
                Product & Location Tags
              </span>
              <div className="flex flex-wrap gap-2">
                {[
                  ...(result.hashtags.productService || []),
                  ...(result.hashtags.location || []),
                ].map((tag, idx) => (
                  <span
                    key={idx}
                    className="text-xs font-medium px-2.5 py-1 rounded-lg bg-slate-950 text-emerald-300 border border-slate-800"
                  >
                    {tag}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Section 4 & 5: SEO Keywords and Call to Action */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* SEO Keywords (2 Cols) */}
        <div className="lg:col-span-2 bg-slate-900/90 border border-slate-800 rounded-2xl p-6 backdrop-blur-md">
          <div className="flex items-center justify-between pb-4 border-b border-slate-800">
            <div>
              <h4 className="text-base font-bold text-white flex items-center gap-2">
                <Search className="w-4 h-4 text-cyan-400" />
                High-Intent SEO Keywords
              </h4>
              <p className="text-xs text-slate-400 mt-0.5">
                Optimized for search algorithms, Reels discovery, and Google ranking
              </p>
            </div>

            <button
              onClick={() => copyToClipboard(getAllKeywordsText(), 'SEO Keywords')}
              className="px-3 py-1.5 rounded-lg text-xs font-semibold bg-slate-800 hover:bg-cyan-500 hover:text-slate-950 text-slate-200 transition-all flex items-center gap-1.5"
            >
              {copiedSection === 'SEO Keywords' ? (
                <Check className="w-3.5 h-3.5" />
              ) : (
                <Copy className="w-3.5 h-3.5" />
              )}
              Copy Keywords
            </button>
          </div>

          <div className="flex flex-wrap gap-2 mt-4">
            {result.seoKeywords.all.map((kw, idx) => (
              <span
                key={idx}
                className="text-xs font-medium px-3 py-1.5 rounded-lg bg-slate-950 text-slate-200 border border-slate-800 hover:border-slate-700 flex items-center gap-1.5"
              >
                <Tag className="w-3 h-3 text-cyan-400" />
                {kw}
              </span>
            ))}
          </div>
        </div>

        {/* Call To Action (1 Col) */}
        <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 flex flex-col justify-between backdrop-blur-md">
          <div>
            <div className="flex items-center justify-between pb-4 border-b border-slate-800">
              <h4 className="text-base font-bold text-white flex items-center gap-2">
                <MessageSquare className="w-4 h-4 text-cyan-400" />
                Call to Action
              </h4>
              <span className="text-[11px] text-cyan-400 font-semibold">Conversion</span>
            </div>

            <div className="mt-4 p-4 rounded-xl bg-slate-950/80 border border-cyan-500/20 text-cyan-200 text-sm leading-relaxed font-semibold">
              "{result.callToAction}"
            </div>
            <p className="text-xs text-slate-400 mt-2">
              Based on visible offers, pricing, or realistic business engagement.
            </p>
          </div>

          <div className="mt-6 pt-4 border-t border-slate-800">
            <button
              onClick={() => copyToClipboard(result.callToAction, 'Call to Action')}
              className="w-full py-2 rounded-lg text-xs font-semibold bg-slate-800 hover:bg-cyan-500 hover:text-slate-950 text-slate-200 transition-all flex items-center justify-center gap-1.5"
            >
              {copiedSection === 'Call to Action' ? (
                <Check className="w-3.5 h-3.5" />
              ) : (
                <Copy className="w-3.5 h-3.5" />
              )}
              Copy Call To Action
            </button>
          </div>
        </div>
      </div>

      {/* Section 6: Summary & Visual Highlights */}
      <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-5 backdrop-blur-md">
        <h4 className="text-sm font-bold text-white mb-2">Content Summary & Visual Highlights</h4>
        <p className="text-sm text-slate-300 leading-relaxed">{result.contentSummary}</p>

        {result.detectedContext.visualHighlights?.length > 0 && (
          <div className="mt-3 flex flex-wrap gap-2">
            {result.detectedContext.visualHighlights.map((highlight, idx) => (
              <span
                key={idx}
                className="text-xs bg-slate-950 px-2.5 py-1 rounded-md text-slate-300 border border-slate-800"
              >
                • {highlight}
              </span>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};
